#%RAML 1.0 NamedExample
value:

  -
    MovieID: 1
    MovieName: Bala
    MovieLanguage: ENGLISH
    MovieDuration: 2
    MovieGenre: Comedy
    MovieCast:
      Hero: Ayushman Kurana
      Heroin: Yami
      Director: Amar
      Music: Sachin
  
  -
    MovieID: 2
    MovieName: Karnan
    MovieLanguage: TAMIL
    MovieDuration: 3
    MovieGenre: Action/Drama
    MovieCast:
      Hero: Dhanush
      Heroin: Ajisha
      Director: Mari Selvaraj
      Music: Sana
