#%RAML 1.0 NamedExample
value:

  -
    TheatreID: 1
    TheatreName: PVR
    TheatreLocation: CHENNAI
  
  -
    TheatreID: 2
    TheatreName: PALAZZO
    TheatreLocation: BANGALORE
  
  -
    TheatreID: 3
    TheatreName: GOPAL CINEMAS
    TheatreLocation: HYDERABAD