#%RAML 1.0 Library
usage:
types:
  Movie: !include /exchange_modules/aff3dafa-8738-4429-b9bf-5a690ee044d3/moviedatatype/1.0.0/moviedatatype.raml
  Theater: !include /exchange_modules/aff3dafa-8738-4429-b9bf-5a690ee044d3/theatredatatype/1.0.0/theatredatatype.raml
  Order: !include /exchange_modules/aff3dafa-8738-4429-b9bf-5a690ee044d3/orderdatatype/1.0.0/orderdatatype.raml
