#%RAML 1.0 Library
usage:
types:
  BookMovie: !include /exchange_modules/aff3dafa-8738-4429-b9bf-5a690ee044d3/bookseatsdatatype/1.0.0/bookseatsdatatype.raml
  E-ticket: !include  /exchange_modules/aff3dafa-8738-4429-b9bf-5a690ee044d3/eticketdatatype/1.0.0/eticketdatatype.raml